import type { Retreat } from './types';

export const RETREATS: Retreat[] = [
  {
    slug: 'hawaii-body-mastery-winter-2027',
    title: 'Hawaii Body Mastery Intensive · Seven Days at the Source',
    summary:
      "Seven days on the Big Island where I now teach most of the year. Two daily practices, beach conditioning, the banya, ocean swims, and the long Sunday class. For students of the ARKademy ready to go deep — and anyone serious about beginning.",
    venue: 'A private compound on the Hamakua coast',
    location: 'Big Island, Hawaii',
    startDate: '2027-02-06',
    endDate: '2027-02-13',
    price: 389000,
    deposit: 75000,
    capacity: 12,
    spotsLeft: 4,
    image:
      'https://images.unsplash.com/photo-1545389336-cf090694435e?w=1600&q=85&auto=format&fit=crop',
    format: 'in-person',
    schedule: [
      '5:30 — Sunrise practice on the lanai',
      '7:30 — Cleansing rituals, breakfast',
      '10:00 — Beach conditioning + sea swim',
      '13:00 — Lunch, rest',
      '15:30 — Pranayama & philosophy',
      '17:00 — Banya ritual (Wed/Sat)',
      '19:00 — Dinner, dharma talk',
    ],
    included: [
      'Single-occupancy accommodation in the compound',
      'Three plant-based meals daily, prepared on-site',
      'All practice sessions and teaching',
      'Banya access twice during the retreat',
      'Ocean kayak and snorkel mornings',
      'Airport pickup and drop on the Big Island',
    ],
    notIncluded: ['Flights to Kona (KOA)', 'Personal expenses', 'Massage and bodywork (available on-site)'],
  },
  {
    slug: 'mysore-pilgrimage-2027',
    title: 'Mysore Pilgrimage · 14 Days in South India',
    summary:
      "A return to the place that shaped me. Two weeks in Gokulam — daily Mysore self-practice at the institute, philosophy and chanting in the afternoons, the quiet life of the neighborhood in between. For students who have practiced primary series for at least two years.",
    venue: 'Gokulam · heritage home',
    location: 'Mysore, Karnataka, India',
    startDate: '2027-01-08',
    endDate: '2027-01-22',
    price: 449000,
    deposit: 95000,
    capacity: 10,
    spotsLeft: 3,
    image:
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1600&q=85&auto=format&fit=crop',
    format: 'in-person',
    schedule: [
      '5:30 — Mysore self-practice at the institute',
      '8:00 — Breakfast, sangha time',
      '10:00 — Sanskrit chanting & philosophy',
      'Afternoon — Rest, reading, optional walks',
      '17:00 — Pranayama or led practice',
      '19:00 — Dinner, dharma talk',
    ],
    included: [
      'Twin-share heritage accommodation',
      'Daily sattvic meals',
      'All practice and teaching with Arkady',
      'Local airport pickup and drop',
      'Excursions to Chamundi Hill and the palace',
      'Pre- and post-retreat preparation calls',
    ],
    notIncluded: ['International flights', 'Visa fees', 'Personal expenses'],
  },
  {
    slug: 'baltic-banya-summer-2026',
    title: 'Baltic Banya Retreat · The Old Way',
    summary:
      "Six days in the Baltic forests — the banya I grew up with, daily practice in birch and pine, ice plunges, the slow cooking of the long evening table. Drawn from my Russian roots, taught with my yoga lineage. Small group, very specific medicine.",
    venue: 'A forest homestead',
    location: 'Latvia',
    startDate: '2026-07-04',
    endDate: '2026-07-10',
    price: 329000,
    deposit: 70000,
    capacity: 10,
    spotsLeft: 6,
    image:
      'https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=1600&q=85&auto=format&fit=crop',
    format: 'in-person',
    schedule: [
      '7:00 — Forest practice',
      '9:00 — Breakfast, cleansing',
      '12:00 — Banya & cold plunge',
      'Afternoon — Free, optional bodywork',
      '17:00 — Pranayama in the meadow',
      '20:00 — Long dinner, dharma talk',
    ],
    included: [
      'Single-occupancy cabin',
      'All meals from the homestead garden',
      'Daily banya access with all rituals',
      'All practice sessions',
      'Ground transport from Riga',
    ],
    notIncluded: ['Flights to Riga', 'Optional massage and bodywork add-ons'],
  },
];
