import type { Retreat } from './types';

/**
 * Retreat dates and prices intentionally TBA. Placeholders kept so
 * JSON-LD Event schema validates; UI renders "Dates announced soon"
 * and "Inquire" instead.
 */
const TBA_PLACEHOLDER_START = '2099-01-01';
const TBA_PLACEHOLDER_END = '2099-01-07';

export const RETREATS: Retreat[] = [
  {
    slug: 'corfu',
    title: 'Corfu · Seven Days on the Ionian',
    summary:
      "A week on the northeast coast of Corfu — olive groves above, the sea below, a small white-walled retreat house in between. Twice-daily practice, long Mediterranean lunches, and the slowness the island has been teaching travelers for three thousand years.",
    venue: 'Villa Avlaki',
    location: 'Kassiopi, Corfu, Greece',
    startDate: TBA_PLACEHOLDER_START,
    endDate: TBA_PLACEHOLDER_END,
    datesTba: true,
    price: 0,
    priceTba: true,
    deposit: 0,
    capacity: 14,
    spotsLeft: 14,
    image:
      'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=1600&q=85&auto=format&fit=crop',
    format: 'in-person',
    schedule: [
      '6:30 — Sunrise practice on the terrace',
      '8:30 — Greek breakfast, swim',
      '11:00 — Pranayama & philosophy',
      'Afternoon — Free, optional boat to Erikoussa',
      '17:30 — Restorative practice in the olive grove',
      '20:00 — Long table dinner with the chef',
    ],
    included: [
      'Twin-share sea-view room',
      'All meals — Greek breakfast, taverna lunch, family dinner',
      'House wine with dinner',
      'All practice and teaching with Arkady',
      'One private boat day on the Ionian',
      'Airport pickup from Corfu (CFU)',
    ],
    notIncluded: ['Flights to Corfu', 'Optional bodywork add-ons'],
  },
  {
    slug: 'montenegro',
    title: 'Montenegro · The Hidden Adriatic',
    summary:
      "A week on the Bay of Kotor — Europe's least-known fjord, a UNESCO-protected stretch of water flanked by 1500-meter limestone walls. Mornings on the dock, afternoons in the village, evenings with a chef who cooks like his grandmother.",
    venue: 'Stone villa above Perast',
    location: 'Bay of Kotor, Montenegro',
    startDate: TBA_PLACEHOLDER_START,
    endDate: TBA_PLACEHOLDER_END,
    datesTba: true,
    price: 0,
    priceTba: true,
    deposit: 0,
    capacity: 12,
    spotsLeft: 12,
    image:
      'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=1600&q=85&auto=format&fit=crop',
    format: 'in-person',
    schedule: [
      '7:00 — Asana on the stone terrace',
      '9:00 — Slow breakfast, swim from the dock',
      '11:30 — Sutra study & pranayama',
      'Afternoon — Village walks, optional kayak',
      '17:30 — Long-hold practice, restorative',
      '20:00 — Dinner with views over the bay',
    ],
    included: [
      'Single-occupancy room in the villa',
      'All meals — locally sourced, mostly plant-based',
      'House wine with dinner',
      'All practice with Arkady',
      'One day hike to Our Lady of the Rocks',
      'Ground transport from Tivat (TIV)',
    ],
    notIncluded: ['Flights to Tivat or Podgorica', 'Optional spa add-ons'],
  },
  {
    slug: 'southern-turkey',
    title: 'Southern Turkey · The Lycian Coast',
    summary:
      "A week on the Turquoise Coast — practice in pine forests above the sea, swims in coves the Romans named, dinners under bougainvillea. Anatolia is one of the oldest yogic-adjacent landscapes on earth. You can feel it in the rocks.",
    venue: 'A renovated Ottoman manor outside Kaş',
    location: 'Kaş, Antalya Province, Turkey',
    startDate: TBA_PLACEHOLDER_START,
    endDate: TBA_PLACEHOLDER_END,
    datesTba: true,
    price: 0,
    priceTba: true,
    deposit: 0,
    capacity: 14,
    spotsLeft: 14,
    image:
      'https://images.unsplash.com/photo-1589481169991-40ee02888551?w=1600&q=85&auto=format&fit=crop',
    format: 'in-person',
    schedule: [
      '6:30 — Pranayama in the pine grove',
      '7:30 — Asana practice',
      '9:30 — Long Turkish breakfast',
      'Midday — Swim, optional boat to Kekova',
      '16:30 — Yin & restorative',
      '20:00 — Mezze dinner under the vines',
    ],
    included: [
      'Twin-share room in the manor',
      'All meals — traditional Turkish home cooking',
      'All practice and teaching',
      'One full-day boat to the sunken city of Kekova',
      'Hamam visit',
      'Airport pickup from Dalaman (DLM) or Antalya (AYT)',
    ],
    notIncluded: ['Flights', 'Personal expenses in the village'],
  },
  {
    slug: 'georgia',
    title: 'Georgia · The Caucasus Mountains',
    summary:
      "A retreat across the country of Georgia — half in Tbilisi (the old city, the wine, the sulphur baths), half in Kazbegi at the foot of the high Caucasus. Practice at elevation, walk through monasteries that predate Europe, eat food that has not changed in a thousand years.",
    venue: 'Old town apartment + mountain lodge',
    location: 'Tbilisi & Kazbegi, Georgia',
    startDate: TBA_PLACEHOLDER_START,
    endDate: TBA_PLACEHOLDER_END,
    datesTba: true,
    price: 0,
    priceTba: true,
    deposit: 0,
    capacity: 10,
    spotsLeft: 10,
    image:
      'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=1600&q=85&auto=format&fit=crop',
    format: 'in-person',
    schedule: [
      '7:00 — Mountain practice (Kazbegi) or terrace (Tbilisi)',
      '9:00 — Georgian breakfast',
      '11:00 — Pranayama & sutra study',
      'Afternoon — Monastery visits, walks, sulphur baths',
      '17:30 — Long-hold restorative',
      '20:00 — Supra dinner with toasts',
    ],
    included: [
      'Boutique hotels in both locations',
      'All meals + traditional supras with local wine',
      'All practice and teaching',
      'Gergeti Trinity Church hike',
      'Sulphur bath day in Tbilisi',
      'Airport pickup from Tbilisi (TBS)',
    ],
    notIncluded: ['International flights to Tbilisi', 'Personal souvenirs'],
  },
  {
    slug: 'miami',
    title: 'Miami · Winter Practice Intensive',
    summary:
      "For North American students who want the work without the long flight. Daily practice on a private rooftop, ocean swims, the city for those who want it and the cushion for those who don't. The only urban retreat I run all year.",
    venue: 'Private rooftop above Collins Avenue',
    location: 'Miami Beach, Florida, USA',
    startDate: TBA_PLACEHOLDER_START,
    endDate: TBA_PLACEHOLDER_END,
    datesTba: true,
    price: 0,
    priceTba: true,
    deposit: 0,
    capacity: 16,
    spotsLeft: 16,
    image:
      'https://images.unsplash.com/photo-1535498730771-e735b998cd64?w=1600&q=85&auto=format&fit=crop',
    format: 'in-person',
    schedule: [
      '6:30 — Rooftop practice at first light',
      '8:30 — Breakfast, ocean swim',
      '11:00 — Pranayama & philosophy',
      'Afternoon — Free; optional walks, beach, art deco district',
      '17:00 — Evening practice',
      '19:30 — Group dinner (out, three nights)',
    ],
    included: [
      'Single-occupancy condo with kitchen',
      'Breakfast and lunch daily',
      'All practice on the rooftop',
      'Three group dinners',
      'Beach access and ocean swims',
    ],
    notIncluded: ['Flights to Miami (MIA)', 'Dinner three nights', 'Personal expenses'],
  },
];
